services:
  ac-cost-web:
    build: .
    container_name: ac-cost-web
    restart: unless-stopped
    ports:
      - "5656:5656"
    env_file:
      - .env
    volumes:
      - /DATA/AppData/ac-cost-web/config:/config
    networks:
      - observatorio_default
      - bridge_net

networks:
  observatorio_default:
    external: true
  bridge_net:
    driver: bridge
